package https.edelivery_egov_bg.services.integration;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-06-21T21:00:11.455+03:00
 * Generated source version: 3.4.4
 *
 */
@WebService(targetNamespace = "https://edelivery.egov.bg/services/integration", name = "IEDeliveryIntegrationService")
@XmlSeeAlso({com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, org.datacontract.schemas._2004._07.edelivery_common.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class, ObjectFactory.class, org.datacontract.schemas._2004._07.edelivery_common_datacontracts.ObjectFactory.class})
public interface IEDeliveryIntegrationService {

    @WebMethod(operationName = "SendElectronicDocumentOnBehalfOf", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendElectronicDocumentOnBehalfOf")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendElectronicDocumentOnBehalfOf", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendElectronicDocumentOnBehalfOfResponse")
    @RequestWrapper(localName = "SendElectronicDocumentOnBehalfOf", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.SendElectronicDocumentOnBehalfOf")
    @ResponseWrapper(localName = "SendElectronicDocumentOnBehalfOfResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.SendElectronicDocumentOnBehalfOfResponse")
    @WebResult(name = "SendElectronicDocumentOnBehalfOfResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public java.lang.Integer sendElectronicDocumentOnBehalfOf(

        @WebParam(name = "subject", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String subject,
        @WebParam(name = "docBytes", targetNamespace = "https://edelivery.egov.bg/services/integration")
        byte[] docBytes,
        @WebParam(name = "docNameWithExtension", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String docNameWithExtension,
        @WebParam(name = "docRegNumber", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String docRegNumber,
        @WebParam(name = "senderType", targetNamespace = "https://edelivery.egov.bg/services/integration")
        org.datacontract.schemas._2004._07.edelivery_common.EProfileType senderType,
        @WebParam(name = "senderUniqueIdentifier", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String senderUniqueIdentifier,
        @WebParam(name = "senderPhone", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String senderPhone,
        @WebParam(name = "senderEmail", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String senderEmail,
        @WebParam(name = "senderFirstName", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String senderFirstName,
        @WebParam(name = "senderLastName", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String senderLastName,
        @WebParam(name = "receiverType", targetNamespace = "https://edelivery.egov.bg/services/integration")
        org.datacontract.schemas._2004._07.edelivery_common.EProfileType receiverType,
        @WebParam(name = "receiverUniqueIdentifier", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String receiverUniqueIdentifier,
        @WebParam(name = "serviceOID", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String serviceOID,
        @WebParam(name = "operatorEGN", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String operatorEGN
    );

    @WebMethod(operationName = "CheckSubjectHasRegistration", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/CheckSubjectHasRegistration")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/CheckSubjectHasRegistration", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/CheckSubjectHasRegistrationResponse")
    @RequestWrapper(localName = "CheckSubjectHasRegistration", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.CheckSubjectHasRegistration")
    @ResponseWrapper(localName = "CheckSubjectHasRegistrationResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.CheckSubjectHasRegistrationResponse")
    @WebResult(name = "CheckSubjectHasRegistrationResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public org.datacontract.schemas._2004._07.edelivery_common.DcSubjectRegistrationInfo checkSubjectHasRegistration(

        @WebParam(name = "identificator", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String identificator
    );

    @WebMethod(operationName = "GetSubjectInfo", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSubjectInfo")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSubjectInfo", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSubjectInfoResponse")
    @RequestWrapper(localName = "GetSubjectInfo", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.GetSubjectInfo")
    @ResponseWrapper(localName = "GetSubjectInfoResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.GetSubjectInfoResponse")
    @WebResult(name = "GetSubjectInfoResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public org.datacontract.schemas._2004._07.edelivery_common_datacontracts.DcSubjectInfo getSubjectInfo(

        @WebParam(name = "electronicSubjectId", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String electronicSubjectId,
        @WebParam(name = "operatorEGN", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String operatorEGN
    );

    @WebMethod(operationName = "GetRegisteredInstitutions", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetRegisteredInstitutions")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetRegisteredInstitutions", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetRegisteredInstitutionsResponse")
    @RequestWrapper(localName = "GetRegisteredInstitutions", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.GetRegisteredInstitutions")
    @ResponseWrapper(localName = "GetRegisteredInstitutionsResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.GetRegisteredInstitutionsResponse")
    @WebResult(name = "GetRegisteredInstitutionsResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public org.datacontract.schemas._2004._07.edelivery_common_datacontracts.ArrayOfDcInstitutionInfo getRegisteredInstitutions()
;

    @WebMethod(operationName = "GetReceivedMessagesList", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetReceivedMessagesList")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetReceivedMessagesList", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetReceivedMessagesListResponse")
    @RequestWrapper(localName = "GetReceivedMessagesList", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.GetReceivedMessagesList")
    @ResponseWrapper(localName = "GetReceivedMessagesListResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.GetReceivedMessagesListResponse")
    @WebResult(name = "GetReceivedMessagesListResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public org.datacontract.schemas._2004._07.edelivery_common.ArrayOfDcMessage getReceivedMessagesList(

        @WebParam(name = "onlyNew", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.Boolean onlyNew,
        @WebParam(name = "operatorEGN", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String operatorEGN
    );

    @WebMethod(operationName = "SendMessageOnBehalfOf", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendMessageOnBehalfOf")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendMessageOnBehalfOf", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendMessageOnBehalfOfResponse")
    @RequestWrapper(localName = "SendMessageOnBehalfOf", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.SendMessageOnBehalfOf")
    @ResponseWrapper(localName = "SendMessageOnBehalfOfResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.SendMessageOnBehalfOfResponse")
    @WebResult(name = "SendMessageOnBehalfOfResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public java.lang.Integer sendMessageOnBehalfOf(

        @WebParam(name = "message", targetNamespace = "https://edelivery.egov.bg/services/integration")
        org.datacontract.schemas._2004._07.edelivery_common.DcMessageDetails message,
        @WebParam(name = "senderType", targetNamespace = "https://edelivery.egov.bg/services/integration")
        org.datacontract.schemas._2004._07.edelivery_common.EProfileType senderType,
        @WebParam(name = "senderUniqueIdentifier", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String senderUniqueIdentifier,
        @WebParam(name = "senderPhone", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String senderPhone,
        @WebParam(name = "senderEmail", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String senderEmail,
        @WebParam(name = "senderFirstName", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String senderFirstName,
        @WebParam(name = "senderLastName", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String senderLastName,
        @WebParam(name = "receiverType", targetNamespace = "https://edelivery.egov.bg/services/integration")
        org.datacontract.schemas._2004._07.edelivery_common.EProfileType receiverType,
        @WebParam(name = "receiverUniqueIdentifier", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String receiverUniqueIdentifier,
        @WebParam(name = "serviceOID", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String serviceOID,
        @WebParam(name = "operatorEGN", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String operatorEGN
    );

    @WebMethod(operationName = "SendElectronicDocument", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendElectronicDocument")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendElectronicDocument", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendElectronicDocumentResponse")
    @RequestWrapper(localName = "SendElectronicDocument", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.SendElectronicDocument")
    @ResponseWrapper(localName = "SendElectronicDocumentResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.SendElectronicDocumentResponse")
    @WebResult(name = "SendElectronicDocumentResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public java.lang.Integer sendElectronicDocument(

        @WebParam(name = "subject", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String subject,
        @WebParam(name = "docBytes", targetNamespace = "https://edelivery.egov.bg/services/integration")
        byte[] docBytes,
        @WebParam(name = "docNameWithExtension", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String docNameWithExtension,
        @WebParam(name = "docRegNumber", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String docRegNumber,
        @WebParam(name = "receiverType", targetNamespace = "https://edelivery.egov.bg/services/integration")
        org.datacontract.schemas._2004._07.edelivery_common.EProfileType receiverType,
        @WebParam(name = "receiverUniqueIdentifier", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String receiverUniqueIdentifier,
        @WebParam(name = "receiverPhone", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String receiverPhone,
        @WebParam(name = "receiverEmail", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String receiverEmail,
        @WebParam(name = "serviceOID", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String serviceOID,
        @WebParam(name = "operatorEGN", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String operatorEGN
    );

    @WebMethod(operationName = "SendMessage", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendMessage")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendMessage", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendMessageResponse")
    @RequestWrapper(localName = "SendMessage", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.SendMessage")
    @ResponseWrapper(localName = "SendMessageResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.SendMessageResponse")
    @WebResult(name = "SendMessageResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public java.lang.Integer sendMessage(

        @WebParam(name = "message", targetNamespace = "https://edelivery.egov.bg/services/integration")
        org.datacontract.schemas._2004._07.edelivery_common.DcMessageDetails message,
        @WebParam(name = "receiverType", targetNamespace = "https://edelivery.egov.bg/services/integration")
        org.datacontract.schemas._2004._07.edelivery_common.EProfileType receiverType,
        @WebParam(name = "receiverUniqueIdentifier", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String receiverUniqueIdentifier,
        @WebParam(name = "receiverPhone", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String receiverPhone,
        @WebParam(name = "receiverEmail", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String receiverEmail,
        @WebParam(name = "serviceOID", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String serviceOID,
        @WebParam(name = "operatorEGN", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String operatorEGN
    );

    @WebMethod(operationName = "GetReceivedMessagesListPaged", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetReceivedMessagesListPaged")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetReceivedMessagesListPaged", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetReceivedMessagesListPagedResponse")
    @RequestWrapper(localName = "GetReceivedMessagesListPaged", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.GetReceivedMessagesListPaged")
    @ResponseWrapper(localName = "GetReceivedMessagesListPagedResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.GetReceivedMessagesListPagedResponse")
    @WebResult(name = "GetReceivedMessagesListPagedResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public org.datacontract.schemas._2004._07.edelivery_common.DcPartialListOfDcMessageHR29GRRX getReceivedMessagesListPaged(

        @WebParam(name = "onlyNew", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.Boolean onlyNew,
        @WebParam(name = "pageNumber", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.Integer pageNumber,
        @WebParam(name = "pageSize", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.Integer pageSize,
        @WebParam(name = "operatorEGN", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String operatorEGN
    );

    @WebMethod(operationName = "GetSentDocumentsContent", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentDocumentsContent")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentDocumentsContent", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentDocumentsContentResponse")
    @RequestWrapper(localName = "GetSentDocumentsContent", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.GetSentDocumentsContent")
    @ResponseWrapper(localName = "GetSentDocumentsContentResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.GetSentDocumentsContentResponse")
    @WebResult(name = "GetSentDocumentsContentResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public org.datacontract.schemas._2004._07.edelivery_common.ArrayOfDcDocument getSentDocumentsContent(

        @WebParam(name = "messageId", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.Integer messageId,
        @WebParam(name = "operatorEGN", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String operatorEGN
    );

    @WebMethod(operationName = "GetSentMessagesListPaged", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentMessagesListPaged")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentMessagesListPaged", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentMessagesListPagedResponse")
    @RequestWrapper(localName = "GetSentMessagesListPaged", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.GetSentMessagesListPaged")
    @ResponseWrapper(localName = "GetSentMessagesListPagedResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.GetSentMessagesListPagedResponse")
    @WebResult(name = "GetSentMessagesListPagedResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public org.datacontract.schemas._2004._07.edelivery_common.DcPartialListOfDcMessageHR29GRRX getSentMessagesListPaged(

        @WebParam(name = "pageNumber", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.Integer pageNumber,
        @WebParam(name = "pageSize", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.Integer pageSize,
        @WebParam(name = "operatorEGN", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String operatorEGN
    );

    @WebMethod(operationName = "SendMessageInReplyTo", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendMessageInReplyTo")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendMessageInReplyTo", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendMessageInReplyToResponse")
    @RequestWrapper(localName = "SendMessageInReplyTo", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.SendMessageInReplyTo")
    @ResponseWrapper(localName = "SendMessageInReplyToResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.SendMessageInReplyToResponse")
    @WebResult(name = "SendMessageInReplyToResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public java.lang.Integer sendMessageInReplyTo(

        @WebParam(name = "message", targetNamespace = "https://edelivery.egov.bg/services/integration")
        org.datacontract.schemas._2004._07.edelivery_common.DcMessageDetails message,
        @WebParam(name = "replyToMessageId", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.Integer replyToMessageId,
        @WebParam(name = "serviceOID", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String serviceOID,
        @WebParam(name = "operatorEGN", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String operatorEGN
    );

    @WebMethod(operationName = "GetEDeliveryGeneralStatistics", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetEDeliveryGeneralStatistics")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetEDeliveryGeneralStatistics", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetEDeliveryGeneralStatisticsResponse")
    @RequestWrapper(localName = "GetEDeliveryGeneralStatistics", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.GetEDeliveryGeneralStatistics")
    @ResponseWrapper(localName = "GetEDeliveryGeneralStatisticsResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.GetEDeliveryGeneralStatisticsResponse")
    @WebResult(name = "GetEDeliveryGeneralStatisticsResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public org.datacontract.schemas._2004._07.edelivery_common.DcStatisticsGeneral getEDeliveryGeneralStatistics()
;

    @WebMethod(operationName = "GetSentMessageStatus", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentMessageStatus")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentMessageStatus", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentMessageStatusResponse")
    @RequestWrapper(localName = "GetSentMessageStatus", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.GetSentMessageStatus")
    @ResponseWrapper(localName = "GetSentMessageStatusResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.GetSentMessageStatusResponse")
    @WebResult(name = "GetSentMessageStatusResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public org.datacontract.schemas._2004._07.edelivery_common.DcMessageDetails getSentMessageStatus(

        @WebParam(name = "messageId", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.Integer messageId,
        @WebParam(name = "operatorEGN", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String operatorEGN
    );

    @WebMethod(operationName = "CheckPersonHasRegistration", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/CheckPersonHasRegistration")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/CheckPersonHasRegistration", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/CheckPersonHasRegistrationResponse")
    @RequestWrapper(localName = "CheckPersonHasRegistration", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.CheckPersonHasRegistration")
    @ResponseWrapper(localName = "CheckPersonHasRegistrationResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.CheckPersonHasRegistrationResponse")
    @WebResult(name = "CheckPersonHasRegistrationResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public org.datacontract.schemas._2004._07.edelivery_common.DcPersonRegistrationInfo checkPersonHasRegistration(

        @WebParam(name = "personId", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String personId
    );

    @WebMethod(operationName = "CheckLegalPersonHasRegistration", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/CheckLegalPersonHasRegistration")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/CheckLegalPersonHasRegistration", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/CheckLegalPersonHasRegistrationResponse")
    @RequestWrapper(localName = "CheckLegalPersonHasRegistration", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.CheckLegalPersonHasRegistration")
    @ResponseWrapper(localName = "CheckLegalPersonHasRegistrationResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.CheckLegalPersonHasRegistrationResponse")
    @WebResult(name = "CheckLegalPersonHasRegistrationResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public org.datacontract.schemas._2004._07.edelivery_common.DcLegalPersonRegistrationInfo checkLegalPersonHasRegistration(

        @WebParam(name = "eik", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String eik
    );

    @WebMethod(operationName = "SendMessageWithAccessCode", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendMessageWithAccessCode")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendMessageWithAccessCode", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendMessageWithAccessCodeResponse")
    @RequestWrapper(localName = "SendMessageWithAccessCode", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.SendMessageWithAccessCode")
    @ResponseWrapper(localName = "SendMessageWithAccessCodeResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.SendMessageWithAccessCodeResponse")
    @WebResult(name = "SendMessageWithAccessCodeResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public java.lang.Integer sendMessageWithAccessCode(

        @WebParam(name = "message", targetNamespace = "https://edelivery.egov.bg/services/integration")
        org.datacontract.schemas._2004._07.edelivery_common.DcMessageDetails message,
        @WebParam(name = "receiver", targetNamespace = "https://edelivery.egov.bg/services/integration")
        org.datacontract.schemas._2004._07.edelivery_common_datacontracts.DcMessageWithCodeReceiver receiver,
        @WebParam(name = "serviceOID", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String serviceOID,
        @WebParam(name = "operatorEGN", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String operatorEGN
    );

    @WebMethod(operationName = "GetSentMessagesList", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentMessagesList")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentMessagesList", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentMessagesListResponse")
    @RequestWrapper(localName = "GetSentMessagesList", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.GetSentMessagesList")
    @ResponseWrapper(localName = "GetSentMessagesListResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.GetSentMessagesListResponse")
    @WebResult(name = "GetSentMessagesListResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public org.datacontract.schemas._2004._07.edelivery_common.ArrayOfDcMessage getSentMessagesList(

        @WebParam(name = "operatorEGN", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String operatorEGN
    );

    @WebMethod(operationName = "GetSentDocumentContent", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentDocumentContent")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentDocumentContent", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentDocumentContentResponse")
    @RequestWrapper(localName = "GetSentDocumentContent", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.GetSentDocumentContent")
    @ResponseWrapper(localName = "GetSentDocumentContentResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.GetSentDocumentContentResponse")
    @WebResult(name = "GetSentDocumentContentResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public org.datacontract.schemas._2004._07.edelivery_common.DcDocument getSentDocumentContent(

        @WebParam(name = "documentId", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.Integer documentId,
        @WebParam(name = "operatorEGN", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String operatorEGN
    );

    @WebMethod(operationName = "GetSentMessageContent", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentMessageContent")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentMessageContent", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentMessageContentResponse")
    @RequestWrapper(localName = "GetSentMessageContent", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.GetSentMessageContent")
    @ResponseWrapper(localName = "GetSentMessageContentResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.GetSentMessageContentResponse")
    @WebResult(name = "GetSentMessageContentResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public org.datacontract.schemas._2004._07.edelivery_common.DcMessageDetails getSentMessageContent(

        @WebParam(name = "messageId", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.Integer messageId,
        @WebParam(name = "operatorEGN", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String operatorEGN
    );

    @WebMethod(operationName = "GetReceivedMessageContent", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetReceivedMessageContent")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetReceivedMessageContent", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetReceivedMessageContentResponse")
    @RequestWrapper(localName = "GetReceivedMessageContent", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.GetReceivedMessageContent")
    @ResponseWrapper(localName = "GetReceivedMessageContentResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.GetReceivedMessageContentResponse")
    @WebResult(name = "GetReceivedMessageContentResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public org.datacontract.schemas._2004._07.edelivery_common.DcMessageDetails getReceivedMessageContent(

        @WebParam(name = "messageId", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.Integer messageId,
        @WebParam(name = "operatorEGN", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String operatorEGN
    );

    @WebMethod(operationName = "SendElectronicDocumentWithAccessCode", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendElectronicDocumentWithAccessCode")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendElectronicDocumentWithAccessCode", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/SendElectronicDocumentWithAccessCodeResponse")
    @RequestWrapper(localName = "SendElectronicDocumentWithAccessCode", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.SendElectronicDocumentWithAccessCode")
    @ResponseWrapper(localName = "SendElectronicDocumentWithAccessCodeResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.SendElectronicDocumentWithAccessCodeResponse")
    @WebResult(name = "SendElectronicDocumentWithAccessCodeResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public java.lang.Integer sendElectronicDocumentWithAccessCode(

        @WebParam(name = "subject", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String subject,
        @WebParam(name = "docBytes", targetNamespace = "https://edelivery.egov.bg/services/integration")
        byte[] docBytes,
        @WebParam(name = "docNameWithExtension", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String docNameWithExtension,
        @WebParam(name = "docRegNumber", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String docRegNumber,
        @WebParam(name = "receiver", targetNamespace = "https://edelivery.egov.bg/services/integration")
        org.datacontract.schemas._2004._07.edelivery_common_datacontracts.DcMessageWithCodeReceiver receiver,
        @WebParam(name = "serviceOID", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String serviceOID,
        @WebParam(name = "operatorEGN", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String operatorEGN
    );

    @WebMethod(operationName = "GetSentDocumentStatusByRegNum", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentDocumentStatusByRegNum")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentDocumentStatusByRegNum", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentDocumentStatusByRegNumResponse")
    @RequestWrapper(localName = "GetSentDocumentStatusByRegNum", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.GetSentDocumentStatusByRegNum")
    @ResponseWrapper(localName = "GetSentDocumentStatusByRegNumResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.GetSentDocumentStatusByRegNumResponse")
    @WebResult(name = "GetSentDocumentStatusByRegNumResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public org.datacontract.schemas._2004._07.edelivery_common.DcMessageDetails getSentDocumentStatusByRegNum(

        @WebParam(name = "documentRegistrationNumber", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String documentRegistrationNumber,
        @WebParam(name = "operatorEGN", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String operatorEGN
    );

    @WebMethod(operationName = "GetSentDocumentContentByRegNum", action = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentDocumentContentByRegNum")
    @Action(input = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentDocumentContentByRegNum", output = "https://edelivery.egov.bg/services/integration/IEDeliveryIntegrationService/GetSentDocumentContentByRegNumResponse")
    @RequestWrapper(localName = "GetSentDocumentContentByRegNum", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.GetSentDocumentContentByRegNum")
    @ResponseWrapper(localName = "GetSentDocumentContentByRegNumResponse", targetNamespace = "https://edelivery.egov.bg/services/integration", className = "https.edelivery_egov_bg.services.integration.GetSentDocumentContentByRegNumResponse")
    @WebResult(name = "GetSentDocumentContentByRegNumResult", targetNamespace = "https://edelivery.egov.bg/services/integration")
    public org.datacontract.schemas._2004._07.edelivery_common.DcDocument getSentDocumentContentByRegNum(

        @WebParam(name = "documentRegistrationNumber", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String documentRegistrationNumber,
        @WebParam(name = "operatorEGN", targetNamespace = "https://edelivery.egov.bg/services/integration")
        java.lang.String operatorEGN
    );
}
